### ISSUE TITLE
Unable to run application 

### ISSUE THREAD

**Issue by srampur** [Logicalis/asn1#10]
Hello,

I am new to the go and apologize in advance if I am asking a silly question.
I have downloaded and trying run 'go build' and I seem to be able to successfully build. But I do not see any executable to run. Do we have an application to test this library with takes ber/der files as input?

**Comment by mhcerri** [comment]
Hi. That's just a library to decode and encode Asn.1.

**Comment by srampur** [comment]
Thank you, do we have example application using this library for decoding
and encoding? I thought *_test.go files are applications.

**Comment by mhcerri** [comment]
Sorry. The code inside the _test.go files is simply unit tests. But there's one example of how using it on the documentation.
